on:
  schedule:
    - cron: 5 4 * * *
  workflow_dispatch:
jobs:
  macos-latest:
    runs-on: macos-latest
    steps:
      - run: sw_vers
  macos-10-15:
    runs-on: macos-10.15
    steps:
      - run: sw_vers
  macos-11:
    runs-on: macos-11
    continue-on-error: true
    steps:
      - run: sw_vers
