on:
  schedule:
    - cron: 4 5 * * *
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/sniff-images.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/sniff-images.yml
jobs:
  sniff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: actions/virtual-environments

      - uses: actions/checkout@v2
        with:
          path: this

      - run: this/.github/actions/get-images.rb > images.json

      - run: echo "stamp=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
        if: ${{ !github.event.pull_request }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[cron] versions ${{ env.stamp }}'
        if: ${{ !github.event.pull_request }}

      - run: cat images.json
        if: ${{ github.event.pull_request }}
