on:
  schedule:
    - cron: 5 4 * * *
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/sniff.yml
jobs:
  macOS:
    strategy:
      matrix:
        os:
          - macos-10.15
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/sw_vers
      id: sw_vers
    - uses: ./.github/actions/persist
      with:
        key: ${{ matrix.os }}-version
        value: ${{ steps.sw_vers.outputs.macOS }}
    - uses: ./.github/actions/persist
      with:
        key: ${{ matrix.os }}-swift
        value: ${{ steps.sw_vers.outputs.swift }}

  xcode:
    strategy:
      matrix:
        os:
          - macos-10.15
    runs-on: ${{ matrix.os }}
    steps:
    - run: |
        for xcode in $(mdfind kMDItemCFBundleIdentifier = com.apple.dt.Xcode); do
          v=$(mdls -raw -name kMDItemVersion "$xcode")
          echo "XcodeVersions=$XcodeVersions $v" >> $GITHUB_ENV
        done
    - uses: actions/checkout@v2
    - uses: ./.github/actions/persist
      with:
        key: ${{ matrix.os }}-xcodes
        value: ${{ env.XcodeVersions }}

  persist:
    runs-on: ubuntu-latest
    needs: macOS
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/persist
      id: sw_vers
      with:
        first-column: env
    - uses: jsdaniell/create-json@v1
      with:
        name: versions.json
        json: ${{ steps.sw_vers.outputs.json }}

    - uses: stefanzweifel/git-auto-commit-action@v4
      if: ${{ !github.event.pull_request }}

    - run: cat versions.json | jq
      if: ${{ github.event.pull_request }}
