on:
  schedule:
    - cron: 5 4 * * *
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/sniff.yml
jobs:
  os:
    strategy:
      matrix:
        os:
          - macos-10.15
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
    continue-on-error: ${{ matrix.os == 'ubuntu-16.04' }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/sw_vers
      id: sw_vers
    - uses: ./.github/actions/persist
      with:
        key: ${{ matrix.os }}-version
        value: ${{ steps.sw_vers.outputs.os }}
    - uses: ./.github/actions/persist
      with:
        key: ${{ matrix.os }}-swift
        value: ${{ steps.sw_vers.outputs.swift }}

  xcode:
    strategy:
      matrix:
        os:
          - macos-10.15
    runs-on: ${{ matrix.os }}
    steps:
    - run: |
        for xcode in $(mdfind kMDItemCFBundleIdentifier = com.apple.dt.Xcode); do
          V=$(mdls -raw -name kMDItemVersion "$xcode")
          v="$v $V"
        done
        echo "XcodeVersions=$v" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - uses: ./.github/actions/persist
      with:
        key: ${{ matrix.os }}-xcodes
        value: ${{ env.XcodeVersions }}

  persist:
    runs-on: ubuntu-latest
    needs:
      - os
      - xcode
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/persist
      id: sw_vers
      with:
        first-column: env
    - uses: jsdaniell/create-json@v1
      with:
        name: versions.json
        json: ${{ steps.sw_vers.outputs.json }}

    - run: echo "stamp=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
      if: ${{ !github.event.pull_request }}
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: '[cron] ${{ env.stamp }}'
      if: ${{ !github.event.pull_request }}

    - run: cat versions.json | jq
      if: ${{ github.event.pull_request }}
